opam-version: "2.0"
name: "CertiGraph"
version: "1.1"
maintainer: "CertiGraph team"
homepage: "https://github.com/CertiGraph/CertiGraph"
dev-repo: "git+https://github.com/CertiGraph/CertiGraph.git"
bug-reports: "https://github.com/CertiGraph/CertiGraph/issues"
license: "MIT"
authors: ["Aquinas Hobor"
    "Shengyi Wang"
    "Anshuman Mohan"
    "Andrew W. Appel"
]
build: [
    make "-j%{jobs}%"
]
install: [
    make "install"
]
depends: [
    "coq" {>= "9.1" & < "9.2~"}
    "coq-vst" {= "2.16"}
]
synopsis: "A library for verifying graph-manipulating programs"
description: """
CertiGraph is a library for verifying graph-manipulating programs.
"""
