name: build

on:
  push:
    branches:
      - live  # forall push/merge in live
  pull_request:
    branches:
      - "**"  # forall submitted Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        coq_version:
          - '8.18'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: './coq-certigraph.opam'
          coq_version: ${{ matrix.coq_version }}
