name: build

on:
  push:
    branches:
      - live  # forall push/merge in live
  pull_request:
    branches:
      - "**"  # forall submitted Pull Requests

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - 'rocq/rocq-prover:9.1'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v4
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: './coq-certigraph.opam'
          custom_image: ${{ matrix.image }}
